version: "3.8"
services:
  db:
    container_name: postgres_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"